name: code-quality-checks

on:
    pull_request:
    push:
        branches: [trunk]

jobs:
    typecheck:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v6

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install

            - run: bun run typecheck

    # lint and fomatting quality checks
    format:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v6

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install

            - run: bun run format:check

    lint:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v6

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install

            - run: bun run lint
